all: main

remake: clean main

unitTest: unitTest.o
	g++ -g -std=c++11 unitTest.o parse.o memory.o trace.o -o RunUnitTest.exe

unitTest.o: unitTest.cpp
	g++ -g -std=c++11 -c unitTest.cpp parse.cpp memory.cpp trace.cpp

main: main.o
	g++ -g -std=c++11 main.o parse.o memory.o trace.o debug.o dispatch.o branch.o condition.o jump_sub.o single_op.o trap_int.o -o RunMe.exe

main.o: main.cpp
	g++ -g -std=c++11 -c main.cpp parse.cpp trace.cpp memory.cpp dispatch.cpp branch.cpp condition.cpp jump_sub.cpp single_op.cpp trap_int.cpp debug.cpp

filenames := main.o parse.o memory.o trace.o unitTest.o debug.o dispatch.o RunMe.exe RunUnitTest.exe

files := $(strip $(foreach f,$(filenames),$(wildcard $(f))))

clean:
ifneq ($(files),)
	rm -f $(files)
endif
